linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  gosec:
    excludes:
      - G402
      - G404
  revive:
    rules:
      - name: var-declaration
        disabled: true
issues:
  exclude:
    - S1000
linters:
  enable-all: true
  disable:
    - funlen
    - nlreturn
    - wrapcheck
    - gomnd
    - cyclop
    - err113
    - exhaustruct
    - wsl
    - lll
    - dupl
    - varnamelen
    - gomoddirectives
    - gocognit
    - tagliatelle
    - errorlint
    - gofumpt
    - noctx
    - gosec
    - testpackage
    - gci
    - musttag
    - gofmt
    - ireturn
    - depguard
    - durationcheck
    - gocyclo
    - exhaustive
    - mnd
    - intrange
