version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/missed-blocks-checker.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - 386
nfpms:
  - vendor: 🐹 Quokka Stake
    maintainer: Sergey <freak12techno@gmail.com>
    formats:
      - deb
      - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
